 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/personal_messages", type: :request do
  # PersonalMessage. As you add validations to PersonalMessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PersonalMessage.create! valid_attributes
      get personal_messages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      personal_message = PersonalMessage.create! valid_attributes
      get personal_message_url(personal_message)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_personal_message_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      personal_message = PersonalMessage.create! valid_attributes
      get edit_personal_message_url(personal_message)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PersonalMessage" do
        expect {
          post personal_messages_url, params: { personal_message: valid_attributes }
        }.to change(PersonalMessage, :count).by(1)
      end

      it "redirects to the created personal_message" do
        post personal_messages_url, params: { personal_message: valid_attributes }
        expect(response).to redirect_to(personal_message_url(PersonalMessage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PersonalMessage" do
        expect {
          post personal_messages_url, params: { personal_message: invalid_attributes }
        }.to change(PersonalMessage, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post personal_messages_url, params: { personal_message: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested personal_message" do
        personal_message = PersonalMessage.create! valid_attributes
        patch personal_message_url(personal_message), params: { personal_message: new_attributes }
        personal_message.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the personal_message" do
        personal_message = PersonalMessage.create! valid_attributes
        patch personal_message_url(personal_message), params: { personal_message: new_attributes }
        personal_message.reload
        expect(response).to redirect_to(personal_message_url(personal_message))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        personal_message = PersonalMessage.create! valid_attributes
        patch personal_message_url(personal_message), params: { personal_message: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested personal_message" do
      personal_message = PersonalMessage.create! valid_attributes
      expect {
        delete personal_message_url(personal_message)
      }.to change(PersonalMessage, :count).by(-1)
    end

    it "redirects to the personal_messages list" do
      personal_message = PersonalMessage.create! valid_attributes
      delete personal_message_url(personal_message)
      expect(response).to redirect_to(personal_messages_url)
    end
  end
end
